version: "3"

services:

  postgres:
    build:
      context: .
      dockerfile: ./docker/local/postgres/Dockerfile
    image: postgres_rapihogar_db:14
    container_name: container_rapihogar_db
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./dumps:/dumps

  # TODO: quizas no tiene sentido usar un nginx
  nginx:
    build: ./docker/local/nginx
    ports:
      - 80:80
    depends_on:
      - web
    restart: "on-failure"

  web:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    image: image_rapihogar_backend_app
    container_name: container_rapihogar_backend_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    expose:
      - 8000

volumes:
  postgresql_data:
